---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '00:00'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '00:00'
    groups:
      golang-x:
        patterns:
          - 'golang.org/x/*'
          - 'google.golang.org/*'
      kong:
        patterns:
          - 'github.com/alecthomas/kong'
      prometheus:
        patterns:
          - 'github.com/prometheus/*'
      go-dependencies:
        patterns:
          - '*'
